### ISSUE TITLE
[client-shell] `taskcluster pulse-listen` command

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster#1066]
Read about pulse here:
https://wiki.mozilla.org/Auto-tools/Projects/Pulse

It would be cool to have a command to inspect pulse exchanges...
```
taskcluster pulse-listen [--format yaml|json] <exchange> <routingKeyPattern>
```
where 'exchange' is a pulse exchange... Then it'll print messages to terminal as JSON or YAML, like:
```yaml
exchange: ...
routingKeys:
  - ... # primary routing key
  - ... # all the CC'ed routing keys
message: ...
---
exchange: ...
routingKeys:
  - ... # primary routing key
  - ... # all the CC'ed routing keys
message: ...
---
```
Or if `--format json` is specified it could print a JSON blob per line, so that it can be fed into `jq`.

We can store the username/password in the config system for taskcluster-cli... These should also default to `PULSE_USERNAME` and `PULSE_PASSWORD` env vars, if not config values are entered...
Notice: this should primarily be based on the stuff in `config/`...
Maybe also support options `--username` or `--password` to overwrite these...

----
Finally, we do have exchange meta-data... similar to the API references...
See: https://docs.taskcluster.net/manual/integrations/tools/references
Perhaps we can use those to auto-generate commands that will support listening to pulse exchanges...
I see this as just being a way that people don't have to write the entire exchange name in `taskcluster pulse listen <exchange> <routingkey>` command...

Maybe, it's like `taskcluster api queue-events task-created --task-id ...` and then from the reference doc for `queueEvents` it knows that `task-created -> taskCreated` and `taskId -> task-id` is a component of the default routingkey. Hence, it can construct the `<exchange> <routingkey>` pair and listen... 
This might be a later addition... Initial stuff is to just get
