### ISSUE TITLE
[docker-worker] only enable loopbackAudio/Video where necessary

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2862]
In community, we don't need loopback audio/video, for example.  Setting up loopback video, in particular, has us doing all kinds of weird kernel stuff.  If we could configure that support off, then d-w would start up with just a vanilla kernel, and we'd have a much easier time of things.  The monpacker config for community-tc would be pretty simple.

**Comment by djmitche** [comment]
This already exists!!

```yaml
deviceManagement:
  loopbackVideo:
    enabled: false
  loopbackAudio:
    enabled: false
```
