### ISSUE TITLE
try building a CDN "wrapper" backend

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3951]
The idea here would be that the CDN backend uses a CDN to support simple downloads, but defers everything else to another backend.

Something like
```yaml
backends:
  storage:
    backendType: aws
    bucket: all-my-objects
  cdn:
    backendType: cdn
    cdnType: cloudfront  # I suspect CDNs from different clouds are similar enough that
    cdnId: E023985019    # it is OK to just handle them all in the same backend type
    nextBackendId: storage  # defers to the 'storage' backend for everything but simple downloads
backendMap:
  # send public artifact downloads to the CDN
  - backendId: cdn
    when:
      name: {regexp: "^public/"}
  # all other artifacts just use the storage backend directly
  - backendId: storage
    when: all
```

I think this idea of "wrapping" backends could be really powerful.  This is a pretty limited way to experiment with it.
