### ISSUE TITLE
Task Creator fails when given taskQueueId

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4470]
STR:
 * Go to task creator
 * enter
```yaml
retries: 5
created: '2021-02-25T22:26:27.058Z'
deadline: '2021-02-26T22:26:27.058Z'
expires: '2022-02-26T22:26:27.058Z'
taskQueueId: built-in/succeed
schedulerId: taskcluster-ui
tags: {}
payload: {}
extra: {}
metadata:
  name: task
  description: testing
  owner: taskcluster-internal@mozilla.com
  source: https://github.com/taskcluster/generic-worker
```
 * update the datestamps
 * create

You will get a 400 error with some Graphql complaints:

> Field \"provisionerId\" of required type \"String!\" was not provided."

Fix: the GraphQL should be treating this task definition as a single blob of JSON and just handing it off to the `queue.createTask` method, without interpretation.
