### ISSUE TITLE
Possible slackBlocks format for slack notify not working

### ISSUE THREAD

**Issue by AaronMT** [taskcluster/taskcluster#4982]
I've been testing out `task.extra.notify.slackBlocks` and have been unable to POST output (assuming mangled payload is the reason without having an ability to see logs). 

`task.extra.notify.slackText` works. I say possibly because there's no examples of use I can find anywhere and my usage might have a mistake in it. If anyone has used `slackBlocks` with [SlackBlocks ](https://api.slack.com/reference/block-kit/blocks)formatted content before and clarify that would be great.

Tested the following w/o success with a simple section block

```Yaml
 extra:
        notify:
            slackText: 'https://firefox-ci-tc.services.mozilla.com/tasks/${status.taskId} | ${task.metadata.name} | ${task.metadata.source}'
            slackBlocks: |
                {
                    "type": "section",
                    "text": {
                    "type": "plain_text",
                        "text": '${task.metadata.name}'
                    }
                }
```

as well as including the entire `blocks` array in a payload, e.g, a button

```Yaml
            slackBlocks: |
                {
                "blocks": [
                   {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": '${task.metadata.name}'
                        },
                        "accessory": {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "Test"
                            },
                            "value": "click",
                            "action_id": "button-action"
                        }
                   }
                ]
                }
```

(Using https://app.slack.com/block-kit-builder as a playground for copying syntax)

Any tips appreciated here.

**Comment by AaronMT** [comment]
Had a chance to re-test. Had a malformed payload as an array is required without the need to define "blocks". 

This works

```Yaml
 slackBlocks: |
                [
                  {
                      "type": "section",
                      "text": {
                        "type": "plain_text",
                        "text": "This is a test.",
                        "emoji": true
                      }
                  }
                ]
```
