### ISSUE TITLE
Make a one step setup for Taskcluster

### ISSUE THREAD

**Issue by mostlygeek** [taskcluster/taskcluster#5444]
Taskcluster is really difficult and complex to setup quickly.   I would like a one step script (.sh, .py, .whatever) that creates a cluster for me (someone without much knowledge) to get a cluster to play with and learn on. 

Some asks / ideas for v0.1 of this scripts: 

* give it a GCP API key and it'll create a K8s cluster with all necessary microservices and dependencies (rabbitmq, postgresql, etc) already configured to work together 
* gives me a URL https://mysubdomain.<???> that I can access after the script runs

**Comment by lotas** [comment]
I had created this ticket in JIRA couple of months ago: FCP-50. It  can be used as a starting point or ideas for discussion. Contents below:

Current dev-deployment  process involves several manual steps:
* provisioning unique public IP for dev deployment
* adding domain name → IP mapping in AWS’s Route53 
* issuing manually with cert-bot certificate and using manual DNS verification in Rotue53
* uploading generated certificate manually back to gcloud to be used with GLB ingress
* repeating some of the steps each time password expires (each 3 months)
* every dev needs to repeat those steps 

All of this can be improved and manual steps can be avoided with using  `ingress-nginx` and `cert-manager`

TODO:

Install single `ingress-nginx` in the `taskcluster-dev` cluster and assign single public IP   
```sh
# provisional command to do so:
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm install ingress-nginx/ingress-nginx \
  --name nginx-ingress \
  --namespace ingress-nginx \
  --set controller.service.loadBalancerIP="$LOAD_BALANCER_IP" \
  -f nginx-ingress-values.yaml \
  --debug
```

2. Install and configure cert-manger https://cert-manager.io/docs/  

```sh
# Provisional commands

helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install \
  --name cert-manager \
  --namespace cert-manager \
  --version vX.Y.Z \
  jetstack/cert-manager \
  --set installCRDs=true

# add specific cloud issuers
kubectl apply -f ./certbot-issuers.yaml
```
`certbot-issuers.yaml` should include:
* ClusterIssers that use Route53 for top-level domains like `username.takscluster-dev.net`
* or letsencrypt issuers only to use Route53 wildcard feature `*.taskclsuter-dev.net` → `LOAD_BALANCER_IP`

3. Change ingress configuration to tell that it will use `ingress-nginx` instead, and take care of issuing certificates automatically:

```yaml
ingress:
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/acme-http01-edit-in-place: 'true'
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: 'nginx'
    ingress.kubernetes.io/force-ssl-redirect: true
```

4. Update corresponding documentation.


Outcome: having implemented this once, all dev deployments could be done to numerous domains, without any of manual DNS & cert steps
