### ISSUE TITLE
Take a firefox ci decision task, and work out how to transform it to run under generic-worker

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5734]
In order to run docker-worker tasks under generic-worker, it is desirable to have the facility to take a docker-worker task, and transform it into a generic-worker task.

This transformation eventually could be performed in several places:
* inside generic-worker itself; first identify that the task has a docker-worker payload, transform it to a native generic-worker format, and then internally execute that, so that to all intents and purposes the task author need not be concerned that the transformation took place
* inside taskgraph; in this case, the better approach is probably to directly generate generic-worker tasks rather than to generate docker-worker as an intermediary step. The task building mechanics used by firefox-ci appears to be [here](https://searchfox.org/mozilla-central/rev/88f285c5163f73abd209d4f73cfa476660351982/taskcluster/gecko_taskgraph/transforms/task.py#323-821)
* inside a standalone tool that can be used from multiple contexts, such as inside a task itself

We have decided that a transformation process is more desirable than hardcoding the interpretation of a docker-worker payload inside generic-worker directly, since that is likely to introduce a larger code footprint of greater complexity. It also would not be so flexible, and make it harder to move this logic elsewhere at a later point in time, and require worker updates to all affected worker pools any time changes are desired.

There is also the possibility of introducing the transformation in more than one place, such as in taskgraph and inside the worker directly, to ease the migration of tasks in real world deployments from docker-worker to generic-worker. Potentially once all tasks are migrated, and direct execution of docker-worker style task payloads are no longer required, the capability can be deprecated and eventually removed from one or more sources, but e.g. the standalone tool may still be useful for users that wish not to migrate. None of this _needs to be_ decided now. We can first determine what the transformation steps are, write code that can transform the payload, inject this into the places it makes sense to do so (bullet points above) and then review the situation in the future to see if it makes sense to simplify by removing support in one or more places this transformation capability was added.

In order to know how to reliably transform task payloads from one format to the other, the first step is to work out how to transform a single real-world docker-worker task the equivalent generic-worker task, and make sure it works. That is what this github issue is for.

**Comment by petemoore** [comment]
Here is a real world decision task from firefox-ci deployment of taskcluster:

* in [treeherder](https://treeherder.mozilla.org/jobs?repo=mozilla-central&revision=ca2873779214f6109ffe1b23e1455350294ac325&selectedTaskRun=XJZwMq2zRI6ZXs7KveM5GQ.0)
* in [taskcluster](https://firefox-ci-tc.services.mozilla.com/tasks/XJZwMq2zRI6ZXs7KveM5GQ)

Note this example task expires on 20 October 2023, so here is a copy of the task definition, so that this information still exists after that date:

```
provisionerId: gecko-3
workerType: decision
taskQueueId: gecko-3/decision
schedulerId: gecko-level-3
projectId: none
taskGroupId: XJZwMq2zRI6ZXs7KveM5GQ
dependencies: []
requires: all-completed
routes:
  - tc-treeherder.v2.mozilla-central.ca2873779214f6109ffe1b23e1455350294ac325
  - index.gecko.v2.mozilla-central.latest.taskgraph.decision
  - >-
    index.gecko.v2.mozilla-central.revision.ca2873779214f6109ffe1b23e1455350294ac325.taskgraph.decision
  - index.gecko.v2.mozilla-central.pushlog-id.40334.decision
  - notify.email.ctuns@mozilla.com.on-failed
  - notify.email.ctuns@mozilla.com.on-exception
priority: lowest
retries: 0
created: '2022-10-20T10:58:21.912Z'
deadline: '2022-10-21T10:58:21.912Z'
expires: '2023-10-20T10:58:21.912Z'
scopes:
  - assume:repo:hg.mozilla.org/mozilla-central:branch:default
  - queue:route:notify.email.ctuns@mozilla.com.*
  - in-tree:hook-action:project-gecko/in-tree-action-3-*
  - index:insert-task:gecko.v2.mozilla-central.*
payload:
  env:
    HG_STORE_PATH: /builds/worker/checkouts/hg-store
    GECKO_BASE_REV: 330c69218a931b3504d44c867539ed6083521be5
    GECKO_HEAD_REF: ca2873779214f6109ffe1b23e1455350294ac325
    GECKO_HEAD_REV: ca2873779214f6109ffe1b23e1455350294ac325
    MOZ_AUTOMATION: '1'
    TASKCLUSTER_CACHES: /builds/worker/checkouts
    GECKO_BASE_REPOSITORY: https://hg.mozilla.org/mozilla-unified
    GECKO_HEAD_REPOSITORY: https://hg.mozilla.org/mozilla-central
    PYTHONDONTWRITEBYTECODE: '1'
  cache:
    gecko-level-3-checkouts-sparse-v3: /builds/worker/checkouts
  image: >-
    mozillareleases/gecko_decision:4.0.0@sha256:9f69fe08c28e3cb3cc296451f0a2735df6e25d0e3c877ea735ef1b7f0b345b06
  command:
    - /builds/worker/bin/run-task
    - '--gecko-checkout=/builds/worker/checkouts/gecko'
    - '--gecko-sparse-profile=build/sparse-profiles/taskgraph'
    - '--'
    - bash
    - '-cx'
    - >
      cd /builds/worker/checkouts/gecko && ln -s /builds/worker/artifacts
      artifacts && ./mach --log-no-times taskgraph decision --pushlog-id='40334'
      --pushdate='1666263365' --project='mozilla-central'
      --owner='ctuns@mozilla.com' --level='3' --tasks-for='hg-push'
      --repository-type=hg --base-repository="$GECKO_BASE_REPOSITORY"
      --base-rev="$GECKO_BASE_REV" --head-repository="$GECKO_HEAD_REPOSITORY"
      --head-ref="$GECKO_HEAD_REF" --head-rev="$GECKO_HEAD_REV" 
  features:
    chainOfTrust: true
    taskclusterProxy: true
  artifacts:
    public:
      path: /builds/worker/artifacts
      type: directory
      expires: '2023-10-20T10:58:21.912Z'
    public/docker-contexts:
      path: /builds/worker/checkouts/gecko/docker-contexts
      type: directory
      expires: '2022-10-27T10:58:21.912Z'
  maxRunTime: 3600
metadata:
  name: Gecko Decision Task
  owner: ctuns@mozilla.com
  source: >-
    https://hg.mozilla.org/mozilla-central/raw-file/ca2873779214f6109ffe1b23e1455350294ac325/.taskcluster.yml
  description: >-
    The task that creates all of the other tasks in the task graph ([Treeherder
    job](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=ca2873779214f6109ffe1b23e1455350294ac325&selectedTaskRun=XJZwMq2zRI6ZXs7KveM5GQ))
tags:
  kind: decision-task
  createdForUser: ctuns@mozilla.com
extra:
  notify:
    email:
      link:
        href: >-
          https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=ca2873779214f6109ffe1b23e1455350294ac325
        text: Treeherder Jobs
  tasks_for: hg-push
  treeherder:
    symbol: D
    machine:
      platform: gecko-decision
```
