### ISSUE TITLE
d2g: incorrect escaping of arguments

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6470]
D2g does not correctly escape arguments. For example, with this task payload:

```yaml
payload:
  artifacts:	
    public/build.tar.gz:
      path: /etc/passwd' artifact0; whoami; echo foo > /root/bar; cp 'foo
      expires: '2024-05-28T16:12:56.693817Z'
      type: file
```

you would be able to escape the podman container. Note, d2g does not provide a security boundary, so escaping the podman container is not a security concern (you do not even need to run payloads inside a container if you do not want to). Despite not a security concern, it is of course still a bug and incorrect behaviour.

Caused by:
```go
fmt.Sprintf("podman cp '%s:%s' %s", containerName, dwPayload.Artifacts[gwArtifacts[i].Name].Path, gwArtifacts[i].Path))
```

Obviously we need to properly escape arguments here. We should check all the escaping/encoding of d2g, and maybe even consider running a fuzzer against it.

Credit: @Eijebong reported this
