### ISSUE TITLE
GitHub service does not track non-GitHub originated events

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6598]
The example of this that got me to file this is that tasks created from a cron hook (or any hook, I guess) don't end up with any status in the GitHub UI. For example, [this task](https://firefox-ci-tc.services.mozilla.com/tasks/RkoivSmDRKOkGQ_k8stSrg) was created from a hook, and created a whole bunch of other tasks, none of which showed up in GitHub. The impact of this is that when they fail, the failures are more or less invisible, as it is very difficult to find them through the Taskcluster UI.

From a Taskcluster user perspective this is surprising behaviour: regardless of _what_ is creating tasks, I would expect them to show their status on the commit they are associated with.

(I'm not sure it's needed, but for posterity here is the payload of the task from above, showing that `checks` is even in the routes)
```
provisionerId: app-services-3
workerType: decision-gcp
taskQueueId: app-services-3/decision-gcp
schedulerId: app-services-level-3
projectId: none
taskGroupId: RkoivSmDRKOkGQ_k8stSrg
dependencies: []
requires: all-completed
routes:
  - checks
  - >-
    index.project.application-services.v2.branch.main.latest.taskgraph.decision-nightly
  - >-
    index.project.application-services.v2.branch.main.revision.c5c55468c1f7883455963f21f6498896806b7091.taskgraph.decision-nightly
  - >-
    index.project.application-services.v2.branch.main.revision.c5c55468c1f7883455963f21f6498896806b7091.taskgraph.cron.RkoivSmDRKOkGQ_k8stSrg
priority: lowest
retries: 5
created: '2023-10-05T05:00:56.623Z'
deadline: '2023-10-06T05:00:56.623Z'
expires: '2024-10-04T05:00:57.623Z'
scopes:
  - assume:repo:github.com/mozilla/application-services:cron:nightly
payload:
  env:
    REPOSITORIES: '{"appservices":"Application Services"}'
    MOZ_FETCHES_DIR: /builds/worker/fetches
    ANDROID_SDK_ROOT: /builds/worker/android-sdk
    TASKCLUSTER_CACHES: /builds/worker/checkouts
    APPSERVICES_HEAD_REF: main
    APPSERVICES_HEAD_REV: c5c55468c1f7883455963f21f6498896806b7091
    APPSERVICES_BASE_REPOSITORY: https://github.com/mozilla/application-services
    APPSERVICES_HEAD_REPOSITORY: https://github.com/mozilla/application-services
    APPSERVICES_REPOSITORY_TYPE: git
    APPSERVICES_PIP_REQUIREMENTS: taskcluster/requirements.txt
  cache:
    app-services-level-3-checkouts-v1: /builds/worker/checkouts
  image: >-
    mozillareleases/taskgraph:decision-mobile-35a3e77038af77191b9eb65d822a2ee34839e44d176859a69c5086f60101947c@sha256:b8638ba91bff32e72f09f74b170a0197093886a91fae1ad0cf757fd0e2c21bf0
  command:
    - /usr/local/bin/run-task
    - '--appservices-checkout=/builds/worker/checkouts/vcs'
    - '--task-cwd=/builds/worker/checkouts/vcs'
    - '--'
    - bash
    - '-cx'
    - >
      ln -s /builds/worker/artifacts artifacts && ~/.local/bin/taskgraph
      decision --pushlog-id='0' --pushdate='0' --project='application-services'
      --message="" --owner='cron@noreply.mozilla.org' --level='3'
      --base-repository="$APPSERVICES_BASE_REPOSITORY"
      --head-repository="$APPSERVICES_HEAD_REPOSITORY"
      --head-ref="$APPSERVICES_HEAD_REF" --head-rev="$APPSERVICES_HEAD_REV"
      --repository-type="$APPSERVICES_REPOSITORY_TYPE" --tasks-for='cron'
      --target-tasks-method=nightly
  features:
    chainOfTrust: true
    taskclusterProxy: true
  artifacts:
    public:
      path: /builds/worker/artifacts
      type: directory
      expires: '2024-10-04T05:00:56.623Z'
    public/docker-contexts:
      path: /builds/worker/checkouts/vcs/docker-contexts
      type: directory
      expires: '2023-10-12T05:00:56.623Z'
  maxRunTime: 1800
metadata:
  name: Decision Task for cron job nightly
  owner: cron@noreply.mozilla.org
  source: >-
    https://github.com/mozilla/application-services/raw/c5c55468c1f7883455963f21f6498896806b7091/.taskcluster.yml
  description: >-
    Created by a [cron
    task](https://firefox-ci-tc.services.mozilla.com/tasks/OKZauBWuSXe77aGyowil8g)
tags:
  kind: cron-task
extra:
  cron: >-
    {"job_name":"nightly","job_symbol":"Nd","quoted_args":"--target-tasks-method=nightly","task_id":"OKZauBWuSXe77aGyowil8g"}
  tasks_for: cron
  treeherder:
    machine:
      platform: gecko-decision
```
