### ISSUE TITLE
taskcluster UI does not show useful errors when data does not match the schema

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6720]
For example, trying to run the `Train` action on https://firefox-ci-tc.services.mozilla.com/tasks/groups/cR2CerRoTNaBQTgz0jjHKA with the following data:
```
datasets:
  devtest:
    - flores_devtest
  mono-src:
    - opus_MaCoCu/v2
  mono-trg:
    - news-crawl_news.2021
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015
    - news-crawl_news.2014
    - news-crawl_news.2013
    - news-crawl_news.2012
    - news-crawl_news.2011
    - news-crawl_news.2010
    - news-crawl_news.2009
    - news-crawl_news.2008
    - news-crawl_news.2007
  test:
    - flores_dev
  train:
    - opus_NLLB/v1
    - opus_OpenSubtitles/v2018
experiment:
  backward-model: NOT-YET-SUPPORTED
  best-model: chrf
  bicleaner:
    dataset-thresholds: {}
    default-threshold: 0.1
  mono-max-sentences-src: 100000000
  mono-max-sentences-trg: 20000000
  name: baseline_en_ca
  split-length: 2000000
  spm-sample-size: 10000000
  src: en
  teacher-ensemble: '5'
  trg: ca
  use-opuscleaner: 'true'
  vocab: NOT-YET-SUPPORTED
marian-args:
  decoding-backward:
    beam-size: '12'
    mini-batch-words: '2000'
  decoding-teacher:
    mini-batch-words: '4000'
    precision: float16
  training-backward:
    early-stopping: '5'
  training-student:
    early-stopping: '20'
  training-student-finetuned:
    early-stopping: '20'
  training-teacher:
    early-stopping: '30'
target-stage: all
taskcluster:
  split-chunks: 10
```

...fails with a red bar that says `No Errors`. (Note that `teacher-ensemble` is a string when it must be a number.):
![Screenshot 2023-12-04 at 15-08-23 Task Group - Decision Task (Push) - FirefoxCI](https://github.com/taskcluster/taskcluster/assets/49649/5604164b-32b6-4e54-8386-dd1e3da2fa80)
