### ISSUE TITLE
taskcluster action UI converts floats to numbers

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6721]
On https://firefox-ci-tc.services.mozilla.com/tasks/groups/cR2CerRoTNaBQTgz0jjHKA, I triggered the `Train` hook with these parameters:
```
datasets:
  devtest:
    - flores_devtest
  mono-src:
    - opus_MaCoCu/v2
  mono-trg:
    - news-crawl_news.2021
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015
    - news-crawl_news.2014
    - news-crawl_news.2013
    - news-crawl_news.2012
    - news-crawl_news.2011
    - news-crawl_news.2010
    - news-crawl_news.2009
    - news-crawl_news.2008
    - news-crawl_news.2007
  test:
    - flores_dev
  train:
    - opus_NLLB/v1
    - opus_OpenSubtitles/v2018
experiment:
  backward-model: NOT-YET-SUPPORTED
  best-model: chrf
  bicleaner:
    dataset-thresholds: {}
    default-threshold: 0.0
  mono-max-sentences-src: 100000000
  mono-max-sentences-trg: 20000000
  name: baseline_en_ca
  split-length: 2000000
  spm-sample-size: 10000000
  src: en
  teacher-ensemble: 2
  trg: ca
  use-opuscleaner: 'true'
  vocab: NOT-YET-SUPPORTED
marian-args:
  decoding-backward:
    beam-size: '12'
    mini-batch-words: '2000'
  decoding-teacher:
    mini-batch-words: '4000'
    precision: float16
  training-backward:
    early-stopping: '5'
  training-student:
    early-stopping: '20'
  training-student-finetuned:
    early-stopping: '20'
  training-teacher:
    early-stopping: '30'
target-stage: all
taskcluster:
  split-chunks: 10
```

Note the `default-threshold` of `0.0`. When the task ran, that was converted to a plain `0.0`. Looking at the network requests I see that this was POSTed to https://firefox-ci-tc.services.mozilla.com/graphql:
```
{
  "operationName": "TriggerHook",
  "variables": {
    "hookGroupId": "project-translations",
    "hookId": "in-tree-action-1-train/2921b6001a",
    "payload": {
      "decision": {
        "action": {
          "cb_name": "train",
          "description": "Initiate part or all of the training pipeline",
          "name": "train",
          "symbol": "train",
          "taskGroupId": "OWlP0-_lQ_Czrbg4NSpV-w",
          "title": "Train"
        },
        "push": {
          "branch": "train-en-ca",
          "owner": "mozilla-taskcluster-maintenance@mozilla.com",
          "pushlog_id": "0",
          "revision": "8d4d4d9a5c4a21297c3fbd1d182d32b93568430f"
        },
        "repository": {
          "level": "1",
          "project": "firefox-translations-training",
          "url": "https://github.com/mozilla/firefox-translations-training"
        }
      },
      "user": {
        "input": {
          "datasets": {
            "devtest": [
              "flores_devtest"
            ],
            "mono-src": [
              "opus_MaCoCu/v2"
            ],
            "mono-trg": [
              "news-crawl_news.2021",
              "news-crawl_news.2020",
              "news-crawl_news.2019",
              "news-crawl_news.2018",
              "news-crawl_news.2017",
              "news-crawl_news.2016",
              "news-crawl_news.2015",
              "news-crawl_news.2014",
              "news-crawl_news.2013",
              "news-crawl_news.2012",
              "news-crawl_news.2011",
              "news-crawl_news.2010",
              "news-crawl_news.2009",
              "news-crawl_news.2008",
              "news-crawl_news.2007"
            ],
            "test": [
              "flores_dev"
            ],
            "train": [
              "opus_NLLB/v1",
              "opus_OpenSubtitles/v2018"
            ]
          },
          "experiment": {
            "backward-model": "NOT-YET-SUPPORTED",
            "best-model": "chrf",
            "bicleaner": {
              "dataset-thresholds": {},
              "default-threshold": 0
            },
            "mono-max-sentences-src": 100000000,
            "mono-max-sentences-trg": 20000000,
            "name": "baseline_en_ca",
            "split-length": 2000000,
            "spm-sample-size": 10000000,
            "src": "en",
            "teacher-ensemble": 2,
            "trg": "ca",
            "use-opuscleaner": "true",
            "vocab": "NOT-YET-SUPPORTED"
          },
          "marian-args": {
            "decoding-backward": {
              "beam-size": "12",
              "mini-batch-words": "2000"
            },
            "decoding-teacher": {
              "mini-batch-words": "4000",
              "precision": "float16"
            },
            "training-backward": {
              "early-stopping": "5"
            },
            "training-student": {
              "early-stopping": "20"
            },
            "training-student-finetuned": {
              "early-stopping": "20"
            },
            "training-teacher": {
              "early-stopping": "30"
            }
          },
          "target-stage": "all",
          "taskcluster": {
            "split-chunks": 10
          }
        },
        "taskGroupId": "OWlP0-_lQ_Czrbg4NSpV-w",
        "taskId": "OWlP0-_lQ_Czrbg4NSpV-w"
      }
    }
  },
  "query": "mutation TriggerHook($hookGroupId: ID!, $hookId: ID!, $payload: JSON!) {\n  triggerHook(hookGroupId: $hookGroupId, hookId: $hookId, payload: $payload) {\n    taskId\n    __typename\n  }\n}\n"
}
```

...which shows that `default-threshold` is no longer a float.

In many cases this isn't _terrible_, but when triggering hooks by hand it's not uncommon to download the action input and use it elsewhere (eg: for a second trigger of the hook, to check in somewhere and use as the basis for some tests) - and for these use cases it is a pretty big paper cut (especially when combined with #6720).
```
