### ISSUE TITLE
Command ABORTED on d2g worker

### ISSUE THREAD

**Issue by pyoor** [taskcluster/taskcluster#7255]
**Describe the bug**
As seen intermittently by our fuzzing instances, some instances fail with a `Command ABORTED` error.  See this [task](https://community-tc.services.mozilla.com/tasks/BXWx-CnNRhiaAP7kReXNVw/runs/0/logs/public/logs/live.log) for further details.

These tasks are running on generic worker with the payload converted by d2g.

**Comment by petemoore** [comment]
Note, the task payload is:

```yaml
artifacts:
  project/fuzzing/libfuzzer/corpus:
    expires: '2024-10-08T06:05:05.944404Z'
    path: /tests
    type: directory
  project/fuzzing/private/logs:
    expires: '2024-10-08T06:05:05.944404Z'
    path: /logs/
    type: directory
capabilities:
  devices:
    hostSharedMemory: true
  privileged: true
env:
  FUZZING_GIT_REPOSITORY: git@github.com:MozillaSecurity/fuzzing-tc-config.git
  FUZZING_GIT_REVISION: master
  TASKCLUSTER_FUZZING_POOL: pool18
  TASKCLUSTER_SECRET: project/fuzzing/decision
features:
  taskclusterProxy: true
image:
  namespace: project.fuzzing.orion.libfuzzer.master
  path: public/libfuzzer.tar.zst
  type: indexed-image
maxRunTime: 21600
```

This is converted by d2g to use the following command:

```yaml
command:
  - - bash
    - '-cx'
    - >-
      IMAGE_ID=$(docker load --input dockerimage | sed -n '0,/^Loaded image:
      /s/^Loaded image: //p')

      timeout 21600 docker run -t --name taskcontainer --memory-swap -1
      --pids-limit -1 --privileged -v /dev/shm:/dev/shm
      --add-host=taskcluster:127.0.0.1 --net=host -e FUZZING_GIT_REPOSITORY -e
      FUZZING_GIT_REVISION -e RUN_ID -e TASKCLUSTER_FUZZING_POOL -e
      TASKCLUSTER_INSTANCE_TYPE -e TASKCLUSTER_PROXY_URL -e TASKCLUSTER_ROOT_URL
      -e TASKCLUSTER_SECRET -e TASKCLUSTER_WORKER_LOCATION -e TASK_GROUP_ID -e
      TASK_ID "${IMAGE_ID}" 

      exit_code=$?

      docker cp taskcontainer:/tests artifact0

      docker cp taskcontainer:/logs/ artifact1

      docker rm taskcontainer

      exit "${exit_code}"
maxRunTime: 22500
```

Note the first command has a timeout of 21600 seconds, and should be aborted by the timeout command directly, if it takes longer than 21600 seconds. However, the max run time of the task is 22500 seconds. Since generic worker is aborting the task, this suggests that the `docker cp` / `docker rm` commands are taking > 900s (15 minutes). This seems .... surprising. Unless there are a lot of artifacts to copy to the host?

It may be worth testing running `docker -v $(pwd)/tests:/tests -v $(pwd)/logs artifact1` so that these two directories are mounted on the host directly, rather than copying the contents from the container to the host after the `docker run` command has run.
