### ISSUE TITLE
artifact expiration is not verified at task submission time

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#7416]
[This task](https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/Ujo9jB_GS52cICfFAVTL1Q/definition) was successfully submitted and was scheduled to run. Notable details of its definition include:
```
created: '2024-12-12T19:27:20.756Z'
deadline: '2024-12-13T19:27:20.756Z'
expires: '2025-03-12T19:27:20.756Z'
payload:
  artifacts:
    public/build:
      path: /builds/worker/artifacts
      type: directory
      expires: '2025-12-09T17:17:13.863Z'
```

It was not until it began to run that an error was thrown.

I assume this happens because artifacts are part of the payload, and the Queue doesn't validate that at all. This is still a bit surprising though, in that this is a docker-worker task, and from a distance, it seems like Taskcluster ought to be able to detect this earlier. (I would assume the same problem applies to a generic-worker task, but I haven't been able to verify that.) I don't know if it's possible or practical to fix this, but I wanted to file it in any case.

(It is, of course, fair to assume that the Queue could not possibly catch errors for tasks intended for other worker types, like scriptworker, at submission time.)
