### ISSUE TITLE
Enhancement: default values in ervices config files

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#7523]
Looks like we are not using `config.yml` file properly.

According to spec: https://github.com/taskcluster/taskcluster/blob/main/libraries/config/README.md#configuration-format it should be split in profiles: `default:`, `production:`, `test:` etc, but at the moment all configs are only using defaults+test
And when placing too many env vars into default section like:

```yml
defaults:
  server:
    port: !env:number PORT
    env: !env NODE_ENV
    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY
    keepAliveTimeoutSeconds: !env:number:optional KEEP_ALIVE_TIMEOUT_SECONDS
```

you can't specify a default value other than placing it in code.

A bit of refactoring could be done to move hardcoded defaults into `config.yml/defaults` section and put production/dev into `!env`
