### ISSUE TITLE
Permission issues on windows caches

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#7532]
During my investigation on what went wrong in [bug 1948412](https://bugzilla.mozilla.org/show_bug.cgi?id=1948412), I went down the rabbit hole of windows caches permissions and there are a few things there that are wrong.

1. The cache folder retains all previous ACLs from all the previous users. (see first screenshot, you can count how many attempts I needed to figure all of this out)
2. The owner of the cache folder remains the one that first created it. (1005 in this screenshot)

![Image](https://github.com/user-attachments/assets/56a7a29d-c580-4146-876d-3e66aefaefa2)

3. Those rights are not given recursively and instead the cache relies on files within having rights inheritance on
4. Pip doesn't create its cache with inheritance on.

![Image](https://github.com/user-attachments/assets/296f1616-3f64-40a3-ba7e-b83af09fccf3)

All those screenshots were made while a task was running as the following user, with that cache mounted

![Image](https://github.com/user-attachments/assets/630634c5-88aa-4d67-8bca-a308567a7386)

Task description:

```yaml
provisionerId: windows
workerType: ci11
taskQueueId: windows/ci11
schedulerId: taskcluster-ui
projectId: none
taskGroupId: EnyorDdzRbKIzPtO5J4rWQ
dependencies: []
requires: all-completed
routes: []
priority: lowest
retries: 5
created: '2025-02-18T11:44:00.542Z'
deadline: '2025-02-18T14:44:00.542Z'
expires: '2026-02-18T14:44:00.542Z'
scopes:
  - generic-worker:cache:test
payload:
  env:
    PIP_CACHE_DIR: .task-cache/pip
  mounts:
    - cacheName: test
      directory: .task-cache/pip
  command:
    - '"C:\Program Files\Python313\python.exe" -m venv venv'
    - .\venv\Scripts\activate
    - >-
      pip install --timeout 120 --no-index --find-links
      https://pypi.pub.build.mozilla.org/pub/ vcversioner==2.16.0.0
  maxRunTime: 3600
metadata:
  name: example-task
  owner: name@example.com
  source: http://taskcluster/tasks/create
  description: An **example** task
tags: {}
extra: {}
```

The machine is a freshly installed windows 11 (home edition 😩, don't do that), python 3.13.2, generic worker 81.0.0 with a slight modification regarding `Remote Desktop Users` (see #7531 for why) although this is irrelevant as the issue first appeared on mozilla machines running 77.3.1 on win11.
