### ISSUE TITLE
artifacts expire before tasks even when their expirations match

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#7562]
Consider the following excerpt of a task definition:
```
created: '2024-03-03T14:39:21.990Z'
deadline: '2024-03-04T14:39:21.990Z'
expires: '2025-03-03T14:39:21.990Z'
payload:
  artifacts:
    public:
      path: /builds/worker/artifacts
      type: directory
      expires: '2025-03-03T14:39:21.990Z'
  maxRunTime: 1800
```

...both the task expiration and the artifact expirations are at _exactly_ the same time. However, the artifacts disappear from the task before the task expires from the queue. For example:
![Image](https://github.com/user-attachments/assets/10f7cc39-c3a9-4254-aefd-bea3ad2afcef)

(You can't tell from the screenshot, but trying to download an artifact results in an HTTP 410.)

Presumably this can cause problems with cached tasks (although I guess we could workaround it by ignoring indexed tasks that are close to or after expiry, if we're not doing so already?). I imagine there are probably other impacts are bugs that this could cause.
