### ISSUE TITLE
Artifacts uploaded with a space in their name get uploaded with a plus sign replacing the space

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#7765]
Example of task:

```yaml
retries: 5
created: '2025-06-06T15:22:33.367Z'
deadline: '2025-06-06T18:22:33.367Z'
expires: '2026-06-06T18:22:33.367Z'
taskQueueId: ap/linux-small
projectId: none
tags: {}
scopes: []
payload:
  image: debian:buster-slim
  command:
    - /bin/bash
    - '-c'
    - mkdir /foo && cd foo && echo 1 > "a b"
  artifacts:
    public/foo:
      path: /foo
      type: directory
  maxRunTime: 90
extra: {}
dependencies: []
metadata:
  name: example-task
  description: An **example** task
  owner: name@example.com
  source: https://taskcluster.bananium.fr/tasks/create
schedulerId: taskcluster-ui
```

Run: https://taskcluster.bananium.fr/tasks/a98zOls3S2WkZik_3iX68A

![Image](https://github.com/user-attachments/assets/16824b42-5f8e-4c6b-8f97-9ec83e09109e)

CC @djmitche
